# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conge.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Conge(object):
    def setupUi(self, Conge):
        Conge.setObjectName("Conge")
        Conge.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Conge)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 189))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.debut_conge = QtWidgets.QDateEdit(self.layoutWidget)
        self.debut_conge.setObjectName("debut_conge")
        self.gridLayout.addWidget(self.debut_conge, 3, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 3, 1, 1)
        self.fin_conge = QtWidgets.QDateEdit(self.layoutWidget)
        self.fin_conge.setObjectName("fin_conge")
        self.gridLayout.addWidget(self.fin_conge, 3, 3, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 1, 1, 1)
        self.valider = QtWidgets.QPushButton(self.layoutWidget)
        self.valider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valider.setObjectName("valider")
        self.gridLayout.addWidget(self.valider, 0, 5, 1, 1)
        self.annuler = QtWidgets.QPushButton(self.layoutWidget)
        self.annuler.setMaximumSize(QtCore.QSize(100, 16777215))
        self.annuler.setObjectName("annuler")
        self.gridLayout.addWidget(self.annuler, 0, 4, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 17))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 189, 801, 391))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.horizontalLayoutWidget)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        Conge.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Conge)
        self.statusbar.setObjectName("statusbar")
        Conge.setStatusBar(self.statusbar)

        self.retranslateUi(Conge)
        QtCore.QMetaObject.connectSlotsByName(Conge)

    def retranslateUi(self, Conge):
        _translate = QtCore.QCoreApplication.translate
        Conge.setWindowTitle(_translate("Conge", "MainWindow"))
        self.radioButton_2.setText(_translate("Conge", "congé terminé"))
        self.radioButton.setText(_translate("Conge", "Congé en cours"))
        self.valider.setText(_translate("Conge", "Valider"))
        self.annuler.setText(_translate("Conge", "annuler"))
        self.radioButton_3.setText(_translate("Conge", "congé en attente"))
        self.label.setText(_translate("Conge", "Congé"))
        self.label_2.setText(_translate("Conge", "debut congé"))
        self.label_3.setText(_translate("Conge", "fin congé"))
