# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formlogin(object):
    def setupUi(self, Formlogin):
        Formlogin.setObjectName("Formlogin")
        Formlogin.resize(717, 413)
        self.centralwidget = QtWidgets.QWidget(Formlogin)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 80, 641, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.userNameLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userNameLineEdit)
        self.passWordLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.passWordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passWordLineEdit.setObjectName("passWordLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passWordLineEdit)
        self.erreur = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.erreur.setObjectName("erreur")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.erreur)
        self.valider = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.valider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.valider.setObjectName("valider")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.valider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        Formlogin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Formlogin)
        self.statusbar.setObjectName("statusbar")
        Formlogin.setStatusBar(self.statusbar)

        self.retranslateUi(Formlogin)
        QtCore.QMetaObject.connectSlotsByName(Formlogin)

    def retranslateUi(self, Formlogin):
        _translate = QtCore.QCoreApplication.translate
        Formlogin.setWindowTitle(_translate("Formlogin", "MainWindow"))
        self.userNameLineEdit.setPlaceholderText(_translate("Formlogin", "Username"))
        self.passWordLineEdit.setPlaceholderText(_translate("Formlogin", "Password"))
        self.erreur.setText(_translate("Formlogin", "Erreur"))
        self.valider.setText(_translate("Formlogin", "Valider"))
