# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payement.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Payement(object):
    def setupUi(self, Payement):
        Payement.setObjectName("Payement")
        Payement.resize(747, 516)
        self.centralwidget = QtWidgets.QWidget(Payement)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 691, 481))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(self.widget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 3)
        Payement.setCentralWidget(self.centralwidget)

        self.retranslateUi(Payement)
        QtCore.QMetaObject.connectSlotsByName(Payement)

    def retranslateUi(self, Payement):
        _translate = QtCore.QCoreApplication.translate
        Payement.setWindowTitle(_translate("Payement", "MainWindow"))
        self.label.setText(_translate("Payement", "payement"))
        self.radioButton.setText(_translate("Payement", "Payer"))
        self.radioButton_2.setText(_translate("Payement", "En attente de paye"))
        self.pushButton.setText(_translate("Payement", "Valider"))
