# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'travail.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Travail(object):
    def setupUi(self, Travail):
        Travail.setObjectName("Travail")
        Travail.resize(674, 506)
        self.centralwidget = QtWidgets.QWidget(Travail)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 11, 661, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressource/menu/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.codeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.codeLabel.setObjectName("codeLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.codeLabel)
        self.intitulLabel = QtWidgets.QLabel(self.layoutWidget)
        self.intitulLabel.setObjectName("intitulLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.intitulLabel)
        self.salaireLabel = QtWidgets.QLabel(self.layoutWidget)
        self.salaireLabel.setObjectName("salaireLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.salaireLabel)
        self.primeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.primeLabel.setObjectName("primeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.primeLabel)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateEdit_2)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 2, 1, 1)
        self.tableView = QtWidgets.QTableView(self.layoutWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 3, 0, 1, 4)
        Travail.setCentralWidget(self.centralwidget)

        self.retranslateUi(Travail)
        QtCore.QMetaObject.connectSlotsByName(Travail)

    def retranslateUi(self, Travail):
        _translate = QtCore.QCoreApplication.translate
        Travail.setWindowTitle(_translate("Travail", "MainWindow"))
        self.pushButton.setText(_translate("Travail", "search"))
        self.codeLabel.setText(_translate("Travail", "Code"))
        self.intitulLabel.setText(_translate("Travail", "profession"))
        self.salaireLabel.setText(_translate("Travail", "date"))
        self.primeLabel.setText(_translate("Travail", "durée"))
        self.pushButton_2.setText(_translate("Travail", "Add"))
        self.pushButton_3.setText(_translate("Travail", "Modifier"))
        self.pushButton_4.setText(_translate("Travail", "Remove"))
